### ISSUE TITLE
Where did "jscolorInput" go?

### ISSUE THREAD

**Issue by yindeng** [AnalytixWare/ShinySky#12]
I'm sure there's a reason for removing it, but is it coming back or it's incorporated into a different project? Thanks!

Yindeng

**Comment by xiaodaigh** [comment]
It has been moved to shinysky.incubator (https://github.com/AnalytixWare/shinysky.incubator) as I no longer can spend time maintaining elements that I do not use myself.

**Comment by daattali** [comment]
Hi, I hope you don't mind that I say it here, but I implemented a colourpicker since this one is no longer active

[demo](http://daattali.com/shiny/colourInput/)

**Comment by xiaodaigh** [comment]
@daattali Thanks!!
