### ISSUE TITLE
Use Imports rather than Depends for dependencies

### ISSUE THREAD

**Issue by antoine-sachet** [AnalytixWare/ShinySky#32]
You should use `Imports` instead of `Depends` in the DESCRIPTION. Otherwise you create conflicts, especially since `plyr` conflicts with a lot of packages.

For example, using your package broke my app because `count` was suddenly taken from `plyr` instead of `dplyr`.

BTW you have to use `Imports` if you intend to submit to CRAN.

**Comment by xiaodaigh** [comment]
Done

**Comment by xiaodaigh** [comment]
Sorry guys. I have been inactive.
