### ISSUE TITLE
Wrong Installation information

### ISSUE THREAD

**Issue by shawnbrar** [AnalytixWare/ShinySky#35]
On your [home page](https://github.com/AnalytixWare/ShinySky/), the installation command for `shinysky` is `install.package("shinysky")`. Whereas it should be `install.packages("shinysky")`. The "s" is missing at the end of "packages".
Also when I use `install.packages("shinysky")`, I get an error saying : - 

`Warning message:           
package ‘shinysky’ is not available (for R version 3.6.2)`.

So i have to use the `devtools::install_github()` command to install the package.
Please correct this issue.
And thanks for the amazing tools and widgets.

**Comment by xiaodaigh** [comment]
Thanks
