### ISSUE TITLE
SkinySky installation

### ISSUE THREAD

**Issue by no-shoes** [AnalytixWare/ShinySky#36]
Hello Zhou,

I have tried for a while now to install a package ntbox, which depends on shinysky (https://luismurao.github.io/ntbox_user_guide.html). However, for some unknown reason, shinysky will not install on my system.

I have used the devtools and the removes packages, it seems to connect to download but then fails to install giving a non-zero exit error. rtools has also been set up successfully on my machine (I think)..

Do you have any ideas about what is preventing the installation from happening? I have checked all forums etc.

I am using the most recent version of rstudio on windows 10. Below is the error message.

Many Thanks in advance,

> install_github("AnalytixWare/ShinySky")
Downloading GitHub repo AnalytixWare/ShinySky@HEAD
√  checking for file 'C:\Users\nosho\AppData\Local\Temp\RtmpOy7YXy\remotes4fa4165d7752\AnalytixWare-ShinySky-695b4b9/DESCRIPTION' (413ms)
-  preparing 'shinysky':
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'shinysky_0.1.3.tar.gz'
   
Installing package into ‘C:/Users/nosho/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'shinysky' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'shiny' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'shinysky'
* removing 'C:/Users/nosho/Documents/R/win-library/3.6/shinysky'
Error: Failed to install 'shinysky' from GitHub:
  (converted from warning) installation of package ‘C:/Users/nosho/AppData/Local/Temp/RtmpOy7YXy/file4fa43ab662e7/shinysky_0.1.3.tar.gz’ had non-zero exit status

**Comment by xiaodaigh** [comment]
i can't replicate it. Looks like you would benefit from updating all packages or stick to R 3.6.

Try `update.packages()`

**Comment by no-shoes** [comment]
Hi,

Thanks for the advice here.  Updating packages did not help - but updating
to R to version 4.02 and running package ntbox not in R-Studio did the
trick for me.

Many Thanks

**Comment by xiaodaigh** [comment]
Ok. Glad it's resolved.
