### ISSUE TITLE
Error running ShinyApp

### ISSUE THREAD

**Issue by Pirshtuk** [AnalytixWare/ShinySky#39]
An error has occurred
The application failed to start: exited unexpectedly with code 1

Loading required package: devtools
Loading required package: usethis
Downloading GitHub repo AnalytixWare/ShinySky@HEAD
Warning in i.p(...) :
  'lib = "/opt/R/4.0.5/lib/R/library"' is not writable
Error in value[[3L]](cond) : Failed to install 'shinysky' from GitHub:
  unable to install packages
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by xiaodaigh** [comment]
`'lib = "/opt/R/4.0.5/lib/R/library"' is not writable`

The issue is with your access permissions. Make sure you have the right admin rights
